//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CredentialRegistration.ZeroKeyRPC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZeroKeyRPC.IRPC")]
    public interface IRPC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPC/CredProtect", ReplyAction="http://tempuri.org/IRPC/CredProtectResponse")]
        string CredProtect(string pzw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRPC/CredProtect", ReplyAction="http://tempuri.org/IRPC/CredProtectResponse")]
        System.Threading.Tasks.Task<string> CredProtectAsync(string pzw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRPCChannel : CredentialRegistration.ZeroKeyRPC.IRPC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RPCClient : System.ServiceModel.ClientBase<CredentialRegistration.ZeroKeyRPC.IRPC>, CredentialRegistration.ZeroKeyRPC.IRPC {
        
        public RPCClient() {
        }
        
        public RPCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RPCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RPCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CredProtect(string pzw) {
            return base.Channel.CredProtect(pzw);
        }
        
        public System.Threading.Tasks.Task<string> CredProtectAsync(string pzw) {
            return base.Channel.CredProtectAsync(pzw);
        }
    }
}
