name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET 6.0.x
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
        
    - name: Restore dependencies
      run: nuget restore NFCLoc.sln
      
    - name: Build
      run: msbuild.exe NFCLoc.sln /p:platform="Any CPU" /p:configuration="Release"
      
    - name: Copy resources
      run: copy Credential\NFCLocCredentialProvider\tileimage.bmp bin\Release\Credential
      
    - name: Create Setup file
      run: FOR /F "tokens=*" %g IN ('git rev-parse --short HEAD') do (SET GITHASH=%g)
      run: "%programfiles(x86)%\Inno Setup 6\iscc.exe" /dGitCommitHash="%GITHASH%" "Setup\Script\Script.iss"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NFCLoc
        path: Setup\Result\
